### ISSUE TITLE
How do I even do this lol

### ISSUE THREAD

**Issue by nickdog202** [matthewsmkim1/HQ-Bot#1]
Can someone teach me how to run and use this properly I will send u some money on paypal for it <3

im just getting this error "SyntaxError: multiple statements found while compiling a single statement"

**Comment by matthewsmkim1** [comment]
Yeah sure, sorry I didn't see this until now.
Do you have a mac?
Also, you don't have to pay me money lol.

**Comment by TAPANSHARMA2** [comment]
Can you teach how to use it? I am new to programming, have no clue how to make this run. I use mac.
